language: rust
env:
  global:
    - secure: AxN3lnmiaWamhuhdV3MDELHbhf76qcxFu711s75Y5ztmq07I4BNHAA2bwJ9XLly6hJKC6Er390iTYenWBvjxpu3ZtDqQ9vBDzqaSKsUQoeWFNAPY7fKSJrJlTQkKeJtuXz9vSCrxH3nm+XGUvDeu1z8/Nhbqsq1LjxGPx3zf90c=
install:
  - sudo apt-get install texinfo
script:
  - cargo build --verbose
  - cargo test --verbose
notifications:
  email:
    - tophattedcoder@gmail.com
after_script:
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh