env:
  global:
    - secure: o1PpGrcSWvluiK1m3VydfHiwZjmXApmX5BIZkVF4psCEZjhyEKBk6Uq9g9JAgs2suA+GereVVnVcjdTjCbDzLbXyU2bWg8FfU23hjFVZtil4gMsd3e1cta5AMgohGO8nc8IWEdr6qnybTOtBlbklnf3I88Yak1NE6pWkqHpVTfg=
before_install:
  - yes | sudo add-apt-repository ppa:hansjorg/rust
  - yes | sudo add-apt-repository ppa:cmrx64/cargo
  - sudo apt-get update
  - git clone git://git.savannah.gnu.org/libjit.git
install:
  - sudo apt-get install cargo rust-nightly texinfo
  - cd libjit
  - ./auto_gen.sh
  - ./configure 
  - make
  - sudo make install
  - sudo cp /usr/local/lib/libjit* /usr/lib/
  - cd ..
script:
  - make clean build doc
notifications:
  email:
    - tophattedcoder@gmail.com
after_script:
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh