[package]

name = "jit"
version = "0.0.3"
authors = [ "tophattedcoder@gmail.com" ]
build = "src/build.rs"
links = "jit"

[lib]

name = "jit"
path = "src/jit.rs"

[dependencies]
rust-bindgen = "*"

[build-dependencies]
pkg-config = "~0.0.1"