[package]

name = "jit"
version = "0.0.1"
authors = [ "tophattedcoder@gmail.com" ]
tags = ["compiler", "virtual machine"]

[[lib]]

name = "jit"
path = "src/libjit/jit.rs"

[[lib]]

name = "jit_macros"
path = "src/libjit_macros/jit_macros.rs"
