[package]

name = "jit"
version = "0.0.2"
authors = [ "tophattedcoder@gmail.com" ]
build = "make native"

[[lib]]

name = "jit"
path = "src/libjit/jit.rs"

[[lib]]

name = "jit_macros"
path = "src/libjit_macros/jit_macros.rs"